openapi: 3.0.0
servers:
  - description: BQXT Public
    url: "https://staging.int.bitqt.net/api"
info:
  description: BQTX Public Endpoints
  version: 1.0.0
  title: BQTX PublicEndpoints
  contact:
    email: patrick@bqtx.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: public
paths:
  /public/pairs:
    get:
      tags:
        - public
      summary: pairs list
      description: retrieve list of pairs
      operationId: pairs
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: pairs list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: array
                    items:
                      type: string
                      example:
                        - BTC/USDT
                        - ETH/BTC
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/pairs/{symbol}:
    get:
      tags:
        - public
      summary: pair
      description: retrieve pair info
      operationId: pair
      parameters:
        - $ref: "#/components/parameters/contentType"
        - in: path
          name: symbol
          description: pair symbol
          required: true
          schema:
            type: string
            example: BTC/USDT
      responses:
        "200":
          description: pair info
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: object
                    properties:
                      base:
                        type: string
                        example: BTC
                      quote:
                        type: string
                        example: USDT
                      isActive:
                        type: boolean
                        example: true
                      isMarginActive:
                        type: boolean
                      lostSize:
                        type: number
                      minOrderAmount:
                        type: number
                        example: 0.1
                      amountPrecisone:
                        type: number
                        example: 4
                      pricePrecisone:
                        type: number
                        example: 8
                      totalPrecisone:
                        type: number
                        example: 8
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/fees:
    get:
      tags:
        - public
      summary: fees structure
      description: return object with fees structure
      operationId: fees
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: fees structure
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: object
                    properties:
                      maker:
                        type: number
                        example: 0.1
                      taker:
                        type: number
                        example: 0.1
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/volumes:
    get:
      tags:
        - public
      summary: month daily volumes
      description: return list of daily volumes by pairs
      operationId: fees
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: month daily volumes
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: object
                    properties:
                      pairs(BTC/USDT):
                        type: array
                        items:
                          type: object
                          properties:
                            timestamp:
                              type: string
                              format: date
                            volume:
                              type: number
                              example: 3.4
                      pairs(ETH/BTC):
                        type: array
                        items:
                          type: object
                          properties:
                            timestamp:
                              type: string
                              format: date
                            volume:
                              type: number
                              example: 2.2
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/summary:
    get:
      tags:
        - public
      summary: currencies summary
      description: system status summary based on currencies
      operationId: summary
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: currencies summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: object
                    properties:
                      system_time:
                        type: number
                      currencies:
                        type: object
                        properties:
                          BTC(currency):
                            type: object
                            properties:
                              symbol:
                                type: string
                                example: BTC
                              isActive:
                                type: boolean
                                example: true
                              isCrypto:
                                type: boolean
                                example: true
                              depositActive:
                                type: boolean
                                example: true
                              pendingDeposits:
                                type: integer
                                example: 0
                              withdrawActive:
                                type: boolean
                                example: true
                              pendingWithdrawals:
                                type: integer
                                example: 3
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/tickers:
    get:
      tags:
        - public
      summary: tickers
      description: pairs based tickers
      operationId: tickers
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: pairs tickers
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: object
                    properties:
                      BTC/USDT(pair):
                        type: object
                        properties:
                          last:
                            type: number
                            example: 10016.10932446
                          lowerAsk:
                            type: number
                            example: 9117.04816474
                          highestBid:
                            type: number
                            example: 11914.19355143
                          baseVolume:
                            type: number
                            example: 0.0095
                          quoteVolume:
                            type: number
                            example: 0.0079
                          high24hr:
                            type: number
                            example: 10122.89914221
                          low24hr:
                            type: number
                            example: 9808.61579248
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/trades/{symbol}:
    get:
      tags:
        - public
      summary: trades list
      description: return list of current trades
      operationId: trades list
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: trades list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        maker:
                          type: string
                          format: ObjectID
                        taker:
                          type: string
                          format: ObjectID
                        makerOrderId:
                          type: string
                          format: string
                        takerOrderId:
                          type: string
                          format: string
                        side:
                          type: string
                          example: buy
                        pair:
                          type: string
                          example: BTC/USDT
                        base:
                          type: string
                          example: BTC
                        quote:
                          type: string
                          example: USDT
                        quantity:
                          type: number
                          example: 12.34
                        price:
                          type: number
                          example: 8322.64
                        makerFee:
                          type: number
                          example: 0.1
                        takerFee:
                          type: number
                          example: 0.1
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /public/orders/{symbol}:
    get:
      tags:
        - public
      summary: fees structure
      description: return object with fees structure
      operationId: fees
      parameters:
        - $ref: "#/components/parameters/contentType"
      responses:
        "200":
          description: fees structure
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  result:
                    type: object
                    properties:
                      orderId:
                        type: string
                      side:
                        type: string
                      type:
                        type: string
                      subType:
                        type: string
                      price:
                        type: number
                        example: 8380.32
                      averagePrice:
                        type: number
                        example: 8295.40
                      quantity:
                        type: number
                        example: 0.28
                      cumQuantity:
                        type: number
                        example: 0.30
                      frozenQuantity:
                        type: number
                        example: 0
                      frozenCurrency:
                        type: string
                      symbol:
                        type: string
                      status:
                        type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    BadRequest:
      description: Bad request error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
                example: false
              code:
                type: integer
                example: 400
              type:
                type: string
                example: Bad request
    NotFound:
      description: Not found error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
                example: false
              code:
                type: integer
                example: 404
              type:
                type: string
                example: Not found
    InternalServerError:
      description: Generic internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
                example: false
              code:
                type: integer
                example: 500
              type:
                type: string
                example: Internal server error

  parameters:
    contentType:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        example: application/json
